config/routes.rb
Rails.application.routes.draw do
  get 'topics/new'
  get 'topics/index'
  get 'chats/index'
  get 'chats/show'
  get 'mains/new'
  get 'sessions/new'
  get 'users/edit'
  get 'users/hit'
  get 'pages/index'
  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    get :search, on: :collection
  end
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :topics
  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
  resources :chats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :post, presence: true
  #validates :image, presence: true
  #validates :category, presence: true
  
  belongs_to :user
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :age, presence: true
  
  has_secure_password
  validates :password, presence: true
  
  mount_uploader :image, ImageUploader
  
  has_many :chats,dependent: :destroy
    
  has_many :topics
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: 'topic'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  add_flash_types :success, :info, :warning, :danger
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @my_chats = current_user.chats
    @chat_partners = User.where.not(id:current_user.id)
  end

  def show
    @partner = User.find(params[:id])
    @chats_by_myself = Chat.where(user_id: current_user.id, partner_id: @partner.id)
    @chats_by_other = Chat.where(user_id: @partner.id, partner_id: current_user.id)
    @chats = @chats_by_myself.or(@chats_by_other)
    @chats = @chats.order(:created_at)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite_topics = current_user.favorite_topics
  end

  def create
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.topic_id = params[:topic_id]

    if favorite.save
      redirect_to topics_path, success: 'お気に入りに登録しました'
    else
      redirect_to topics_path, danger: 'お気に入りに登録に失敗しました'
    end
  end
  
  def destroy
    @favorite = Favorite.find_by(user_id: current_user.id, topic_id: params[:topic_id])
    @favorite.destroy
    redirect_to topics_path, success: 'お気に入りを取り消しました'
  end
  
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  def new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email])
    
    if user && user.authenticate(params[:session][:password])
      #binding.pry
      log_in user
      redirect_to mains_new_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  
  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end
  
  private
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  def session_params
    params.require(:session).permit(:email, :password)
  end
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all.includes(:favorite_users)
  end
  
  def new
    @topic = Topic.new
  end
  
  def create
    @topic = current_user.topics.new(topic_params)
    
    if @topic.save
      redirect_to topics_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end

  private
  def topic_params
    params.require(:topic).permit(:image, :post)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def index
  end

  def create
    @user = User.new(user_params)
    #binding.pry
    if @user.save
      log_in(@user)
      redirect_to mains_new_path, success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end
  
  def edit
    #binding.pry
    @user = User.find_by(id: session[:user_id])
  end
  
  def update
    @user = User.find_by(id: session[:user_id])
    #binding.pry
    if @user.update_attributes(user_params)
      redirect_to mains_new_path, success: '更新が完了しました'
    else
      flash.now[:danger] = "更新に失敗しました"
      render :edit
    end
  end
  
  def search
    @users = User.where(residence: params[:residence]).or(User.where(gender: params[:gender])).or(User.where(hobby: params[:hobby_id]))
    
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation,
     :residence, :hobby, :introduction, :age, :gender)
  end
  
  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  

end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/index.html.erb
<div class="rooms">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 col-md-offset-4">
        <% @chat_partners.each do |chat_partner| %>
          <%=link_to "#{chat_partner.email}さんとのトークルーム", "/chats/#{chat_partner.id}" %>
        <%end%>  
      </div>
    </div>
  </div>
</div>
<li>
<%=link_to("メインページへ", "/mains/new")%>
</li>
<li>
<%=link_to("ログアウト", logout_path, method: :delete)%>
</li>

app/views/chats/show.html.erb
<h3 style="text-align:center"><%="#{@partner.email}さんとのチャット"%></h3>
<div id="chats">
  <% @chats.each do |chat|%>
    <%if chat.user_id==current_user.id%>
      <div class="mycomment">
        <p><%=chat.sentence%></p>
      </div>
    <%else%>
      <div class="fukidasi">
        <div class="faceicon">
          <img src="/assets/profile.png" alt="相手">
        </div>
        <div class="chatting">
          <div class="says">
            <p><%=chat.sentence%></p>
          </div>
        </div>
      </div>
    <%end%>
  <%end%>
</div>
<form id="send-form">
  <input type="text" id="sentence" placeholder="入力してね" style="width:30%;">
  <input type="submit" value="送信" id="send">
  <input id="current_user_id" type="hidden" value= "<%=current_user.id%>">
  <input id="partner_id" type="hidden" value= "<%=@partner.id%>">
</form>
<%=link_to("ログアウトする","/users/sign_out",method: :delete)%>

app/views/favorites/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @favorite_topics.each do |topic| %>
    
     <div class="row">
       <div class="col-md-6 col-md-offset-3">
         <div class="topic-index-single">
           <h2 class="topic-author">
             <%= topic.user.name %>
           </h2>
           <%= image_tag topic.image.url %>
           
           <p class="topic-text">
             <%= topic.description %>
           </p>
            
         </div>
       </div>
     </div>
     <% end %>
  </div>
</div>

app/views/mains/new.html.erb
<div class="main-wrapper text-center">
  <div class="container top-hero-container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 col-md-offset-4">
        <%= link_to 'ユーザー検索', search_users_path, class: 'btn btn-block btn-black' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-offset-4 col-md-4 col-md-offset-4">
        <%= link_to '掲示板投稿', new_topic_path, class: 'btn btn-block btn-black' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-offset-4 col-md-4 col-md-offset-4">
        <%= link_to '掲示板一覧', topics_index_path, class: 'btn btn-block btn-black' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-offset-4 col-md-4 col-md-offset-4">
        <%= link_to 'チャット', chats_index_path, class: 'btn btn-block btn-black' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-offset-4 col-md-4 col-md-offset-4">
        <%= link_to '足跡', '#', class: 'btn btn-block btn-black' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-offset-4 col-md-4 col-md-offset-4">
        <%= link_to 'プロフィール編集', users_edit_path, class: 'btn btn-block btn-black' %>
      </div>
    </div>
  </div>
</div>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
     <div class="row">
       <div class="col-md-6 col-md-offset-3">
         <div class="topic-index-single">
           <h2 class="topic-author">
             <%= topic.user.name %>
           </h2>
           <%= image_tag topic.image.url %>
            <% if !topic.favorite_users.include? (current_user) %>
             <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
               <span class='favorite-btn'>&hearts;</span>
             <% end %>
            <% else %>
             <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
               <span class='unfavorite-btn'>&hearts;</span>
             <% end %>
            <% end %>
            <%= topic.favorite_users.count %>
            
           
         </div>
       </div>
     </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">掲示板</h1>
        <%= form_for @topic do |f| %>
          <div class="form-group">
            <%= f.label :image %>
            <%= f.file_field :image%>
          </div>

          <div class="form-group">
            <%= f.label :post %>
            <%= f.text_area :post, class: 'form-control' %>
          </div>

          <%= f.submit '投稿', class: 'btn btn-black btn-block' %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="users-edit-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 user-edit-container">
        <h1 class="text-center text-white">プロフィール登録</h1>
        <%= form_for @user do |f| %>
         <div class="form-group">
           <%= f.label :name, class: 'text-white' %>
           <%= f.text_field :name, class: 'form-control' %>
         </div>
         <div class="form-group">
           <%= f.label :email, class: 'text-white' %>
           <%= f.text_field :email, class: 'form-control' %>
         </div>
         <div class="form-group">
           <%= f.label :gender, class: 'text-white' %>
           <%= f.radio_button :gender, "男" %>男 <%= f.radio_button :gender, "女" %>女  
         </div>
         <div class="form-group">
           <%= f.label :age, class: 'text-white' %>
           <%= f.number_field :age, min: 18, class: 'form-control' %>
         </div>
         <div class="form-group">
           <%= f.label :residence, class: 'text-white' %>
           <%= f.text_field :residence, class: 'form-control' %>
         </div>
         <div class="form-group">
           <%= f.select :hobby_id, [ ["アウトドア",1], ["ドライブ", 2], ["アニメ・マンガ", 3 ] ,["映画", 4], ["ゲーム", 5], ["旅行", 6] ], prompt: "選択してください", class: "hoge" %>
          </div>
         <div class="form-group">
           <%= f.label :introduction, class: 'text-white' %>
           <%= f.text_area :introduction, class: 'form-control' %>
         </div>
         <div class="form-group">
           <%= f.label :password, class: 'text-white' %>
           <%= f.password_field :password, class: 'form-control' %>
         </div>
         <div class="form-group">
           <%= f.label :password_confirmation, class: 'text-white' %>
           <%= f.password_field :password_confirmation, class: 'form-control' %>
         </div>
         
         
         <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        
      </div>
    </div>
  </div>
</div>

app/views/users/hit.html.erb
<div class="users-search-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 user-search-container">
        <h2 class="text-center text-search">検索結果</h2>
        
        <% @users.each do |user| %>
          <tr>
            <td><%= link_to user.name, '#', class: 'btn btn-block btn-search' %></td>
          </tr>
        <% end %>
        <%=link_to"ユーザー検索ページへ", search_users_path, class: 'btn btn-block btn-search' %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 user-new-container">
        <h1 class="text-center text-users">Sign up</h1>
        <%= form_for @user do |f| %>
         <div class="form-group">
           <%= f.label :name, class: 'text-white' %>
           <%= f.text_field :name, class: 'form-control' %>
         </div>
         <div class="form-group">
           <%= f.label :email, class: 'text-white' %>
           <%= f.text_field :email, class: 'form-control' %>
         </div>
         <div class="form-group">
           <%= f.label :gender, class: 'text-white' %>
           <%= f.radio_button :gender, "男" %>男 <%= f.radio_button :gender, "女" %>女  
         </div>
         <div class="form-group">
           <%= f.label :age, class: 'text-white' %>
           <%= f.number_field :age, min: 18, class: 'form-control' %>
         </div>
         <div class="form-group">
           <%= f.label :password, class: 'text-white' %>
           <%= f.password_field :password, class: 'form-control' %>
         </div>
         <div class="form-group">
           <%= f.label :password_confirmation, class: 'text-white' %>
           <%= f.password_field :password_confirmation, class: 'form-control' %>
         </div>
         
         <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path, class: 'text-white' %>
      </div>
    </div>
  </div>
</div>

app/views/users/search.html.erb
<div class="users-search-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 user-search-container">
        <h1 class="text-center text-search">ユーザー検索</h1>
          <%= form_with url: search_users_path, method: :get, local: true do |f| %>
          <div class="form-group">
           <%= f.label :gender, class: 'text-white' %>
           <%= f.radio_button :gender, "男" %>男 <%= f.radio_button :gender, "女" %>女  
          </div>
          <div class="form-group">
            <%= f.label :residence, class: 'text-white' %>
            <%= f.text_field :residence %>
          </div>
          <div class="form-group">
           <%= f.select :hobby_id, [ ["アウトドア",1], ["ドライブ", 2], ["アニメ・マンガ", 3 ] ,["映画", 4], ["ゲーム", 5], ["旅行", 6] ], prompt: "選択してください", class: "hoge" %>
          </div>
          
          
            <%= f.submit "検索", class: 'btn-block btn-white' %>
          <% end %>
          
          
        <h2 class="text-center text-search">検索結果</h2>
        
        <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.name, '#', class: 'btn btn-block btn-search' %></td>
        </tr>
        <% end %>
        
      </div>
    </div>
  </div>
</div>